### ISSUE TITLE
Adventure mode analysis does not update

### ISSUE THREAD

**Issue by jacobspeck** [Razzmatazzz/RemnantSaveManager#13]
perhaps relevant error?

> 
> 2020-05-26 3:04:01 AM: Backup completed (2020-05-26 3:03:53 AM)!
> 2020-05-26 3:04:12 AM: System.InvalidOperationException processing save file change: 'Refresh' is not allowed during an AddNew or EditItem transaction.(   at System.Windows.Data.CollectionView.Refresh()
>    at RemnantSaveManager.MainWindow.<OnSaveTimerElapsed>b__29_0())
> 2020-05-26 3:08:58 AM: Backup completed (2020-05-26 3:07:58 AM)!
> 2020-05-26 3:09:01 AM: Showing current save world analyzer...

**Comment by Razzmatazzz** [comment]
Did you double-click a backup name to change the name but not push "enter" afterwards to save it?

**Comment by Razzmatazzz** [comment]
This should be fixed in the latest release.

**Comment by jacobspeck** [comment]
![wrongadventure](https://user-images.githubusercontent.com/43123945/83008538-4c9d6f00-9fe3-11ea-83e9-d9e438530557.png)
I haven't changed any back up names unfortunately... using 1.95.25 still does not work. There is no error in the log though.

**Comment by jacobspeck** [comment]
I've fixed it!

So I had deleted characters in front of the 218 Cultist in order for it to be the first selected. I had subsequently deleted .sav and .bak files of 1-3 (leaving just 0). I could still play normally without any problem.

I created a new character and noticed they already had an adventure world created (with a bunch of time already spent in it) and now I have a 0 sav/bak as well as 2 (the 218 Cultist was previously in the 3rd position).

But it analyzes the adventure worlds perfectly now 😁

**Comment by Razzmatazzz** [comment]
That makes sense. All the character info is saved in profile.sav and the world info for each character is saved in save_X.sav. The profile.sav file doesn't contain readily identifiable markers of which world save goes with which character, so the analzyer assumes that the first character it finds in profile.sav corresponds to the lowest-numbered save_X.sav file and on from there. It sounds like if the first character gets deleted, the game keeps the corresponding save_X.sav file and things get out of sync (i.e., the analyzer finds the one remaining character in profile.sav and then assumes save_0.sav is the right world data for that character).
